const { EmbedBuilder } = require('discord.js');

module.exports = {
    name: "poll",
    description: 'post a poll' ,
    async run(client, message,args){
        if(!args[0]) return message.reply('please enter valid content');
        const embed = new EmbedBuilder()
        .setTitle('Poll')
        .setColor("#00A3B5")
        .setDescription(args.slice(0).join(' '))
        .setTimestamp()
        .setFooter({text: `New poll generated by ${message.author.tag}`})

        const poll = await message.reply({embeds: [embed]});
        poll.react('<:ZeroTwoAnnoyed:1043930475342868560>');
        poll.react('<:anime_kmsfml:1043930473983913995>');
        
    },
    options: [
        {
            name: 'title',
            description: 'choose a title for your poll',
            type: 3,
            required: true
        },
        {
            name: 'content',
            description: 'Question of the poll',
            type: 3,
            required: true
        }
    ],
    async runSlash(client, interaction){
        const pollTitle = interaction.options.getString('title');
        const pollContent = interaction.options.getString('content');

        const embed = new EmbedBuilder()
        .setTitle(pollTitle)
        .setColor("#00A3B5")
        .setDescription(pollContent)
        .setTimestamp()
        .setFooter({text: `New poll generated by ${interaction.user.tag}`})

        const poll = await interaction.reply({embeds: [embed], fetchReply: true });
        poll.react('<:ZeroTwoAnnoyed:1043930475342868560>');
        poll.react('<:anime_kmsfml:1043930473983913995>');
       
    }
};